"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type Branch={id:string;code:string;name:string};
type Event={id:string;created_at:string;branch_name:string|null;branch_code:string|null;actor_name:string;action:string;entity_type:string;summary:string;details:Record<string,unknown>};
type Control={provider:string|null;backup_enabled:boolean;last_backup_at:string|null;last_verified_at:string|null;evidence_reference:string|null;retention_days:number|null;recovery_contact:string|null;notes:string|null};
type Drill={id:string;performed_at:string;environment:string;outcome:string;duration_minutes:number;restored_through:string|null;evidence_reference:string;notes:string|null};
type Readiness={status:"verified"|"attention"|"not_configured";controls:Control;latest_drill:Drill|null;checks:Array<{label:string;passed:boolean}>;drills:Drill[]};
const day=(offset=0)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
const download=(name:string,body:string,type:string)=>{const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
export default function AuditRecoveryPanel({branches,currentBranch}:{branches:Branch[];currentBranch:Branch}){
 const [tab,setTab]=useState<"audit"|"recovery">("audit"),[events,setEvents]=useState<Event[]>([]),[readiness,setReadiness]=useState<Readiness|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const [branch,setBranch]=useState("all"),[from,setFrom]=useState(day(-30)),[to,setTo]=useState(day()),[entity,setEntity]=useState(""),[query,setQuery]=useState("");
 const [showBackup,setShowBackup]=useState(false),[showDrill,setShowDrill]=useState(false);
 const [backup,setBackup]=useState({provider:"Supabase",enabled:false,last_backup:"",last_verified:"",evidence:"",retention:"7",contact:"",notes:""});
 const [drill,setDrill]=useState({performed:day(),environment:"test",outcome:"passed",duration:"",restored:"",evidence:"",notes:""});
 useEffect(()=>{loadAudit();loadReadiness()},[]);
 async function loadAudit(){setLoading(true);setMessage("");const {data,error}=await supabase.rpc("get_audit_log",{p_branch_id:branch==="all"?null:branch,p_from:`${from}T00:00:00`,p_to:`${to}T23:59:59.999`,p_entity:entity||null,p_query:query||null,p_limit:500});if(error)setMessage(error.message);else setEvents((data??[]) as Event[]);setLoading(false)}
 async function loadReadiness(){const {data,error}=await supabase.rpc("get_backup_readiness");if(error)setMessage(error.message);else{const r=data as Readiness;setReadiness(r);const c=r.controls;setBackup({provider:c.provider??"Supabase",enabled:c.backup_enabled,last_backup:c.last_backup_at?.slice(0,16)??"",last_verified:c.last_verified_at?.slice(0,16)??"",evidence:c.evidence_reference??"",retention:String(c.retention_days??7),contact:c.recovery_contact??"",notes:c.notes??""})}}
 async function saveBackup(e:FormEvent){e.preventDefault();setLoading(true);const {error}=await supabase.rpc("update_backup_controls",{p_provider:backup.provider,p_backup_enabled:backup.enabled,p_last_backup_at:backup.last_backup||null,p_last_verified_at:backup.last_verified||null,p_evidence_reference:backup.evidence,p_retention_days:Number(backup.retention),p_recovery_contact:backup.contact,p_notes:backup.notes});setLoading(false);if(error)setMessage(error.message);else{setShowBackup(false);setMessage("Backup evidence updated.");await Promise.all([loadReadiness(),loadAudit()])}}
 async function saveDrill(e:FormEvent){e.preventDefault();setLoading(true);const {error}=await supabase.rpc("record_recovery_drill",{p_performed_at:`${drill.performed}T12:00:00`,p_environment:drill.environment,p_outcome:drill.outcome,p_duration_minutes:Number(drill.duration),p_restored_through:drill.restored||null,p_evidence_reference:drill.evidence,p_notes:drill.notes});setLoading(false);if(error)setMessage(error.message);else{setShowDrill(false);setMessage("Recovery drill recorded.");await Promise.all([loadReadiness(),loadAudit()])}}
 function exportAudit(){const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;download(`retailflow-audit-${from}-to-${to}.csv`,["Date,Branch,Actor,Action,Entity,Summary",...events.map(e=>[e.created_at,e.branch_code??"System",e.actor_name,e.action,e.entity_type,e.summary].map(q).join(","))].join("\n"),"text/csv;charset=utf-8")}
 async function exportSnapshot(){setLoading(true);const {data,error}=await supabase.rpc("get_recovery_snapshot",{p_branch_id:currentBranch.id});setLoading(false);if(error)setMessage(error.message);else download(`retailflow-${currentBranch.code}-recovery-${day()}.json`,JSON.stringify(data,null,2),"application/json")}
 const status=readiness?.status??"not_configured";
 return <section className="workspace audit-workspace"><header><div><p>Traceability, evidence and business continuity</p><h1>Audit & Recovery</h1></div><div className="audit-tabs"><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}>Audit log</button><button className={tab==="recovery"?"active":""} onClick={()=>setTab("recovery")}>Backup & recovery</button></div></header><div className="audit-body">{message&&<p className={message.includes("updated")||message.includes("recorded")?"notice":"notice error"}>{message}</p>}
 {tab==="audit"?<><section className="audit-filters"><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option>{branches.map(b=><option value={b.id} key={b.id}>{b.code} · {b.name}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Record type<select value={entity} onChange={e=>setEntity(e.target.value)}><option value="">All records</option>{["sales","stock_movements","stock_transfers","purchase_orders","returns","cash_shifts","expenses","inventory_disposals","stocktakes","profiles","staff_branch_assignments","backup_controls","recovery_drills"].map(x=><option key={x}>{x}</option>)}</select></label><label className="audit-search">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Action, person or summary"/></label><button disabled={loading} onClick={loadAudit}>Apply</button><button onClick={exportAudit}>Export CSV</button></section><section className="inventory-card"><div className="inventory-card-title"><div><h2>Recorded activity</h2><p>{events.length} database-recorded events · New activity is captured after migration 018.</p></div></div><div className="table-wrap"><table><thead><tr><th>Date & time</th><th>Branch</th><th>Actor</th><th>Action</th><th>Record</th><th>Summary</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}</td><td>{e.branch_code??"System"}</td><td>{e.actor_name}</td><td><span className="audit-action">{e.action.replaceAll("_"," ")}</span></td><td>{e.entity_type.replaceAll("_"," ")}</td><td>{e.summary}</td></tr>)}{!events.length&&!loading&&<tr><td colSpan={6} className="empty-cell">No matching events yet.</td></tr>}</tbody></table></div></section></>:
 <><section className={`readiness-banner ${status}`}><div><span>{status==="verified"?"✓":"!"}</span><div><small>Backup readiness</small><h2>{status==="verified"?"Verified from recorded evidence":status==="attention"?"Evidence needs attention":"Not configured"}</h2><p>This status uses administrator-recorded evidence. RetailFlow does not independently verify Supabase provider backups.</p></div></div><button onClick={()=>setShowBackup(true)}>Update evidence</button></section><div className="recovery-grid"><section className="inventory-card"><div className="inventory-card-title"><div><h2>Readiness checklist</h2><p>All checks must pass before the system shows “verified”.</p></div></div><div className="readiness-checks">{readiness?.checks.map(c=><article key={c.label}><span className={c.passed?"pass":"fail"}>{c.passed?"✓":"!"}</span><strong>{c.label}</strong><b>{c.passed?"Ready":"Action needed"}</b></article>)}</div></section><aside className="recovery-actions"><section><h2>Recovery drill</h2><p>Test restores only in an isolated sandbox, staging or test project.</p><button onClick={()=>setShowDrill(true)}>Record drill</button></section><section><h2>Continuity snapshot</h2><p>Download current branch inventory plus the last 30 days of sales and stock movements.</p><button disabled={loading} onClick={exportSnapshot}>Download JSON</button><small>This operational snapshot is not a database backup.</small></section></aside></div><section className="inventory-card"><div className="inventory-card-title"><div><h2>Recovery drill history</h2><p>Evidence of safe, isolated restore tests.</p></div></div><div className="table-wrap"><table><thead><tr><th>Performed</th><th>Environment</th><th>Outcome</th><th>Duration</th><th>Restored through</th><th>Evidence</th></tr></thead><tbody>{readiness?.drills.map(d=><tr key={d.id}><td>{new Date(d.performed_at).toLocaleDateString("en-PH",{dateStyle:"medium"})}</td><td>{d.environment}</td><td><span className={`drill-outcome ${d.outcome}`}>{d.outcome}</span></td><td>{d.duration_minutes} min</td><td>{d.restored_through?new Date(d.restored_through).toLocaleString("en-PH"):"—"}</td><td>{d.evidence_reference}</td></tr>)}{!readiness?.drills.length&&<tr><td colSpan={6} className="empty-cell">No recovery drill recorded.</td></tr>}</tbody></table></div></section></>}
 </div>
 {showBackup&&<div className="modal-backdrop"><form className="modal" onSubmit={saveBackup}><div className="modal-title"><div><h2>Backup evidence</h2><p>Enter only details you verified in your provider console.</p></div><button type="button" onClick={()=>setShowBackup(false)}>×</button></div><label className="check-line"><input type="checkbox" checked={backup.enabled} onChange={e=>setBackup({...backup,enabled:e.target.checked})}/> Provider backups are enabled</label><div className="form-grid"><label>Provider<input required value={backup.provider} onChange={e=>setBackup({...backup,provider:e.target.value})}/></label><label>Retention days<input required min="1" type="number" value={backup.retention} onChange={e=>setBackup({...backup,retention:e.target.value})}/></label><label>Last backup<input required={backup.enabled} type="datetime-local" value={backup.last_backup} onChange={e=>setBackup({...backup,last_backup:e.target.value})}/></label><label>Last verified<input required={backup.enabled} type="datetime-local" value={backup.last_verified} onChange={e=>setBackup({...backup,last_verified:e.target.value})}/></label><label className="wide">Evidence reference<input required={backup.enabled} value={backup.evidence} onChange={e=>setBackup({...backup,evidence:e.target.value})} placeholder="Ticket, screenshot filename or provider report"/></label><label className="wide">Recovery contact<input value={backup.contact} onChange={e=>setBackup({...backup,contact:e.target.value})} placeholder="Name, email or escalation channel"/></label><label className="wide">Notes<textarea value={backup.notes} onChange={e=>setBackup({...backup,notes:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setShowBackup(false)}>Cancel</button><button disabled={loading}>Save evidence</button></div></form></div>}
 {showDrill&&<div className="modal-backdrop"><form className="modal" onSubmit={saveDrill}><div className="modal-title"><div><h2>Record recovery drill</h2><p>Never restore over the live production database.</p></div><button type="button" onClick={()=>setShowDrill(false)}>×</button></div><div className="form-grid"><label>Performed date<input required type="date" value={drill.performed} onChange={e=>setDrill({...drill,performed:e.target.value})}/></label><label>Environment<select value={drill.environment} onChange={e=>setDrill({...drill,environment:e.target.value})}><option value="test">Test</option><option value="sandbox">Sandbox</option><option value="staging">Staging</option></select></label><label>Outcome<select value={drill.outcome} onChange={e=>setDrill({...drill,outcome:e.target.value})}><option value="passed">Passed</option><option value="partial">Partial</option><option value="failed">Failed</option></select></label><label>Duration (minutes)<input required min="1" type="number" value={drill.duration} onChange={e=>setDrill({...drill,duration:e.target.value})}/></label><label>Data restored through<input type="datetime-local" value={drill.restored} onChange={e=>setDrill({...drill,restored:e.target.value})}/></label><label>Evidence reference<input required value={drill.evidence} onChange={e=>setDrill({...drill,evidence:e.target.value})}/></label><label className="wide">Notes<textarea value={drill.notes} onChange={e=>setDrill({...drill,notes:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setShowDrill(false)}>Cancel</button><button disabled={loading}>Record drill</button></div></form></div>}
 </section>
}
