"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import JsBarcode from "jsbarcode";
import { supabase } from "../lib/supabase";

type Product={id:string;name:string;sku:string;barcode:string;category:string;price:number;cost:number;stock:number;reorder:number;active:boolean;color:string};
type ProductRow={id:string;name:string;sku:string;barcode:string|null;selling_price:number|string;cost_price:number|string;quantity_on_hand:number|string;reorder_level:number|string;active:boolean;categories:{name:string}|null};
type Movement={id:string;created_at:string;product_name:string;sku:string;movement_type:string;quantity_change:number;notes:string|null};
type StaffProfile={id:string;email:string;full_name:string|null;role:"admin"|"cashier";active:boolean;created_at:string};
const colors=["#dff3e8","#e8efff","#faead8","#f1e8ff","#f3e4da","#dff1f7"];
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});

function BarcodeSvg({value}:{value:string}){
 const ref=useRef<SVGSVGElement|null>(null);
 useEffect(()=>{if(ref.current&&value)JsBarcode(ref.current,value,{format:"CODE128",displayValue:true,fontSize:12,height:42,margin:4})},[value]);
 return <svg ref={ref} aria-label={`Barcode ${value}`}/>;
}

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authError,setAuthError]=useState("");
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(false),[dataError,setDataError]=useState("");
 const [query,setQuery]=useState(""),[cart,setCart]=useState<Record<string,number>>({}),[notice,setNotice]=useState(""),[payment,setPayment]=useState("cash");
 const [view,setView]=useState<"pos"|"inventory"|"staff">("pos"),[movements,setMovements]=useState<Movement[]>([]),[inventoryMessage,setInventoryMessage]=useState("");
 const [profile,setProfile]=useState<StaffProfile|null>(null),[staff,setStaff]=useState<StaffProfile[]>([]),[staffMessage,setStaffMessage]=useState("");
 const [showProduct,setShowProduct]=useState(false),[showStock,setShowStock]=useState(false),[selectedProduct,setSelectedProduct]=useState<Product|null>(null),[editingProduct,setEditingProduct]=useState<Product|null>(null);
 const [productForm,setProductForm]=useState({name:"",sku:"",barcode:"",category:"Grocery",price:"",cost:"",opening:"0",reorder:"5"});
 const [stockForm,setStockForm]=useState({type:"purchase",quantity:"",notes:""});
 const [labelIds,setLabelIds]=useState<string[]>([]),[showLabels,setShowLabels]=useState(false);

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session){loadProducts();loadProfile()}else setProfile(null)},[session]);
 async function signIn(e:FormEvent){e.preventDefault();setAuthError("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setAuthError(error.message)}
 async function loadProducts(){setLoading(true);setDataError("");const {data,error}=await supabase.from("products").select("id,name,sku,barcode,selling_price,cost_price,quantity_on_hand,reorder_level,active,categories(name)").order("name");if(error)setDataError(error.message);else setProducts(((data??[]) as unknown as ProductRow[]).map((p,i)=>({id:p.id,name:p.name,sku:p.sku,barcode:p.barcode??"",price:Number(p.selling_price),cost:Number(p.cost_price),stock:Number(p.quantity_on_hand),reorder:Number(p.reorder_level),active:p.active,category:p.categories?.name??"Uncategorised",color:colors[i%colors.length]})));setLoading(false)}
 async function loadMovements(){const {data,error}=await supabase.from("inventory_movement_history").select("*").order("created_at",{ascending:false}).limit(25);if(!error)setMovements((data??[]) as Movement[])}
 async function loadProfile(){if(!session)return;const {data,error}=await supabase.from("profiles").select("*").eq("id",session.user.id).single();if(error)setDataError(error.message);else{const current=data as StaffProfile;setProfile(current);if(!current.active){await supabase.auth.signOut();setAuthError("Your staff account is inactive.")}}}
 async function openStaff(){setView("staff");const {data,error}=await supabase.from("profiles").select("*").order("created_at");if(error)setStaffMessage(error.message);else setStaff((data??[]) as StaffProfile[])}
 async function updateStaff(id:string,changes:Partial<Pick<StaffProfile,"role"|"active">>){setStaffMessage("");const {error}=await supabase.from("profiles").update({...changes,updated_at:new Date().toISOString()}).eq("id",id);if(error)setStaffMessage(error.message);else{setStaffMessage("Staff access updated successfully.");await openStaff()}}
 async function openInventory(){setView("inventory");await Promise.all([loadProducts(),loadMovements()])}
 async function saveProduct(e:FormEvent){e.preventDefault();setLoading(true);setInventoryMessage("");let {data:cat}=await supabase.from("categories").select("id").eq("name",productForm.category.trim()).maybeSingle();if(!cat){const result=await supabase.from("categories").insert({name:productForm.category.trim()}).select("id").single();cat=result.data;if(result.error){setInventoryMessage(result.error.message);setLoading(false);return}}const values={name:productForm.name.trim(),sku:productForm.sku.trim().toUpperCase(),barcode:productForm.barcode.trim()||null,category_id:cat.id,selling_price:Number(productForm.price),cost_price:Number(productForm.cost||0),reorder_level:Number(productForm.reorder||0)};const result=editingProduct?await supabase.from("products").update(values).eq("id",editingProduct.id):await supabase.from("products").insert({...values,quantity_on_hand:Number(productForm.opening||0)});if(result.error)setInventoryMessage(result.error.message);else{setInventoryMessage(editingProduct?"Product updated successfully.":"Product created successfully.");closeProductModal();await loadProducts()}setLoading(false)}
 function closeProductModal(){setShowProduct(false);setEditingProduct(null);setProductForm({name:"",sku:"",barcode:"",category:"Grocery",price:"",cost:"",opening:"0",reorder:"5"})}
 function editProduct(p:Product){setEditingProduct(p);setProductForm({name:p.name,sku:p.sku,barcode:p.barcode,category:p.category,price:String(p.price),cost:String(p.cost),opening:String(p.stock),reorder:String(p.reorder)});setShowProduct(true)}
 async function generateBarcode(){const {data,error}=await supabase.rpc("generate_internal_barcode");if(error)setInventoryMessage(error.message);else setProductForm(current=>({...current,barcode:String(data)}))}
 async function toggleProduct(p:Product){setInventoryMessage("");const {error}=await supabase.from("products").update({active:!p.active,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)setInventoryMessage(error.message);else{setInventoryMessage(`${p.name} is now ${p.active?"inactive":"active"}.`);await loadProducts()}}
 function toggleLabel(id:string){setLabelIds(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function changeStock(e:FormEvent){e.preventDefault();if(!selectedProduct)return;setLoading(true);setInventoryMessage("");let amount=Number(stockForm.quantity);if(stockForm.type==="adjustment_remove")amount=-Math.abs(amount);else amount=Math.abs(amount);const movementType=stockForm.type==="purchase"?"purchase":"adjustment";const {error}=await supabase.rpc("change_stock",{p_product_id:selectedProduct.id,p_quantity_change:amount,p_movement_type:movementType,p_notes:stockForm.notes});if(error)setInventoryMessage(error.message);else{setInventoryMessage("Stock updated successfully.");setShowStock(false);setStockForm({type:"purchase",quantity:"",notes:""});await Promise.all([loadProducts(),loadMovements()])}setLoading(false)}
 const matchesQuery=(p:Product)=>`${p.name} ${p.sku} ${p.barcode} ${p.category}`.toLowerCase().includes(query.toLowerCase());
 const filtered=products.filter(p=>p.active&&matchesQuery(p)),inventoryFiltered=products.filter(matchesQuery),lines=products.filter(p=>cart[p.id]);
 const subtotal=useMemo(()=>lines.reduce((s,p)=>s+p.price*cart[p.id],0),[cart,lines]),vat=subtotal-subtotal/1.12;
 const add=(p:Product)=>{setNotice("");setCart(c=>({...c,[p.id]:Math.min(p.stock,(c[p.id]??0)+1)}))};
 const qty=(id:string,d:number)=>setCart(c=>{const p=products.find(x=>x.id===id),n=Math.min(p?.stock??0,Math.max(0,(c[id]??0)+d)),u={...c};if(!n)delete u[id];else u[id]=n;return u});
 async function complete(){if(!lines.length)return;setLoading(true);setNotice("");const items=lines.map(p=>({product_id:p.id,quantity:cart[p.id]}));const {error}=await supabase.rpc("complete_sale",{p_items:items,p_payment_method:payment,p_customer_id:null});if(error)setNotice(`Error: ${error.message}`);else{setNotice(`Sale completed — ${peso.format(subtotal)}`);setCart({});await loadProducts()}setLoading(false)}

 if(checking)return <main className="auth-shell"><div className="auth-card"><span className="auth-logo">R</span><p>Opening RetailFlow…</p></div></main>;
 if(!session)return <main className="auth-shell"><form className="auth-card" onSubmit={signIn}><span className="auth-logo">R</span><h1>Welcome to RetailFlow</h1><p>Sign in with a user created in your Supabase project.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@store.com"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>{authError&&<div className="auth-error">{authError}</div>}<button type="submit">Sign in</button><small>Retail Sales & Inventory · Bohol</small></form></main>;
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span>R</span><div>RetailFlow<small>Sales & Inventory</small></div></div><nav aria-label="Main navigation"><button className={view==="pos"?"active":""} onClick={()=>setView("pos")}>▦ <span>Point of Sale</span></button><button>⌂ <span>Dashboard</span></button>{profile?.role==="admin"&&<button className={view==="inventory"?"active":""} onClick={openInventory}>↕ <span>Products & Inventory</span></button>}<button>♙ <span>Customers</span></button><button>⌁ <span>Reports</span></button>{profile?.role==="admin"&&<button className={view==="staff"?"active":""} onClick={openStaff}>⚿ <span>Staff Access</span></button>}</nav><div className="store-card"><span className="status-dot"/>Supabase connected<small>Main Branch · Bohol</small></div><button className="profile" onClick={()=>supabase.auth.signOut()}><span>{session.user.email?.slice(0,2).toUpperCase()}</span><div>{session.user.email}<small>{profile?.role??"Loading"} · Sign out</small></div><b>↗</b></button></aside>
  {view==="pos"?<section className="workspace" id="pos"><header><div><p>{new Intl.DateTimeFormat("en-PH",{dateStyle:"full"}).format(new Date())}</p><h1>Point of Sale</h1></div><div className="header-actions"><button aria-label="Refresh products" onClick={loadProducts}>↻</button><button>＋ New customer</button></div></header>
   <div className="pos-grid"><section className="catalog"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, SKU, or scan barcode…"/><kbd>⌘ K</kbd></label><div className="catalog-heading"><div><h2>Products</h2><p>{loading?"Loading…":`${filtered.length} items available`}</p></div><button>All categories⌄</button></div>
    {dataError&&<div className="setup-warning"><strong>Database setup required</strong><span>{dataError}</span></div>}
    <div className="product-grid">{filtered.map(p=><button className="product-card" onClick={()=>add(p)} key={p.id} disabled={p.stock<=0}><span className="product-art" style={{background:p.color}}>{p.name.split(" ").slice(0,2).map(w=>w[0]).join("")}</span><span className="category">{p.category}</span><strong>{p.name}</strong><small>{p.sku}{p.barcode?` · ${p.barcode}`:""}</small><span className="product-meta"><b>{peso.format(p.price)}</b><em className={p.stock<=p.reorder?"low":""}>{p.stock} in stock</em></span></button>)}</div>
    <div className="quick-stats"><div><span>Live products</span><strong>{products.filter(p=>p.active).length}</strong><small>From Supabase</small></div><div><span>Cart items</span><strong>{Object.values(cart).reduce((a,b)=>a+b,0)}</strong><small>Current transaction</small></div><div><span>Low stock</span><strong>{products.filter(p=>p.active&&p.stock<=p.reorder).length} items</strong><small>Needs attention</small></div></div>
   </section><aside className="cart-panel"><div className="cart-title"><div><h2>Current sale</h2><p>New transaction</p></div><button onClick={()=>setCart({})}>Clear</button></div><button className="customer-row"><span>＋</span><div><strong>Add customer</strong><small>Optional for this sale</small></div><b>›</b></button><div className="cart-lines">{!lines.length&&<div className="empty-cart"><span>▣</span><strong>Your cart is empty</strong><small>Select a product to begin a sale.</small></div>}{lines.map(p=><div className="cart-line" key={p.id}><span className="mini-art" style={{background:p.color}}>{p.name[0]}</span><div className="line-info"><strong>{p.name}</strong><small>{peso.format(p.price)} each</small><div className="stepper"><button onClick={()=>qty(p.id,-1)}>−</button><b>{cart[p.id]}</b><button onClick={()=>qty(p.id,1)}>＋</button></div></div><b>{peso.format(p.price*cart[p.id])}</b></div>)}</div>
    <div className="totals"><div><span>Subtotal</span><b>{peso.format(subtotal)}</b></div><div><span>VAT included</span><b>{peso.format(vat)}</b></div><div className="grand-total"><span>Total</span><b>{peso.format(subtotal)}</b></div></div>{notice&&<p className={notice.startsWith("Error")?"notice error":"notice"}>{notice}</p>}<button className="checkout" disabled={!lines.length||loading} onClick={complete}><span>{loading?"Processing…":"Complete sale"}</span><b>{peso.format(subtotal)} →</b></button><div className="payment-types">{["cash","card","gcash"].map(x=><button key={x} className={payment===x?"selected":""} onClick={()=>setPayment(x)}>{x==="gcash"?"GCash":x[0].toUpperCase()+x.slice(1)}</button>)}</div>
   </aside></div>
  </section>:view==="inventory"?<section className="workspace inventory-workspace"><header><div><p>Products, pricing and stock control</p><h1>Inventory</h1></div><div className="header-actions"><button onClick={()=>{loadProducts();loadMovements()}}>↻ Refresh</button><button disabled={!labelIds.length} onClick={()=>setShowLabels(true)}>▤ Print labels ({labelIds.length})</button><button onClick={()=>setShowProduct(true)}>＋ New product</button></div></header>
   <div className="inventory-body">{inventoryMessage&&<p className={inventoryMessage.includes("successfully")||inventoryMessage.includes("now")?"notice":"notice error"}>{inventoryMessage}</p>}<div className="inventory-stats"><article><span>Active products</span><strong>{products.filter(p=>p.active).length}</strong><small>{products.filter(p=>!p.active).length} inactive</small></article><article><span>Units on hand</span><strong>{products.reduce((sum,p)=>sum+p.stock,0)}</strong><small>Across all products</small></article><article><span>Low stock</span><strong>{products.filter(p=>p.active&&p.stock<=p.reorder).length}</strong><small>Using reorder levels</small></article><article><span>Inventory cost</span><strong>{peso.format(products.reduce((sum,p)=>sum+p.stock*p.cost,0))}</strong><small>Potential margin {peso.format(products.reduce((sum,p)=>sum+p.stock*(p.price-p.cost),0))}</small></article></div>
    <section className="inventory-card"><div className="inventory-card-title"><div><h2>Product catalogue</h2><p>Select products with barcodes to print labels.</p></div><label className="table-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, SKU or barcode…"/></label></div><div className="table-wrap"><table><thead><tr><th><input aria-label="Select all labelled products" type="checkbox" checked={inventoryFiltered.filter(p=>p.barcode).length>0&&inventoryFiltered.filter(p=>p.barcode).every(p=>labelIds.includes(p.id))} onChange={e=>setLabelIds(e.target.checked?inventoryFiltered.filter(p=>p.barcode).map(p=>p.id):[])}/></th><th>Product</th><th>SKU / Barcode</th><th>Price / Cost</th><th>Markup</th><th>On hand</th><th>Status</th><th>Actions</th></tr></thead><tbody>{inventoryFiltered.map(p=><tr key={p.id} className={!p.active?"inactive-row":""}><td><input aria-label={`Select ${p.name} label`} type="checkbox" disabled={!p.barcode} checked={labelIds.includes(p.id)} onChange={()=>toggleLabel(p.id)}/></td><td><strong>{p.name}</strong><small className="cell-sub">{p.category}</small></td><td><code>{p.sku}</code><small className="cell-sub">{p.barcode||"No barcode"}</small></td><td><strong>{peso.format(p.price)}</strong><small className="cell-sub">Cost {peso.format(p.cost)}</small></td><td>{p.cost>0?`${(((p.price-p.cost)/p.cost)*100).toFixed(1)}%`:"—"}</td><td><b>{p.stock}</b><small className="cell-sub">Reorder at {p.reorder}</small></td><td><span className={!p.active?"stock-badge inactive":p.stock<=p.reorder?"stock-badge low":"stock-badge"}>{!p.active?"Inactive":p.stock<=p.reorder?"Low stock":"In stock"}</span></td><td><div className="row-actions"><button className="stock-action" onClick={()=>editProduct(p)}>Edit</button><button className="stock-action" disabled={!p.active} onClick={()=>{setSelectedProduct(p);setShowStock(true)}}>Stock</button><button className="stock-action danger" onClick={()=>toggleProduct(p)}>{p.active?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table></div></section>
    <section className="inventory-card"><div className="inventory-card-title"><div><h2>Recent stock movements</h2><p>Audit trail for receiving, sales and adjustments.</p></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Change</th><th>Notes</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}</td><td><strong>{m.product_name}</strong><small className="cell-sub">{m.sku}</small></td><td><span className="movement-type">{m.movement_type}</span></td><td><b className={Number(m.quantity_change)>0?"positive":"negative"}>{Number(m.quantity_change)>0?"+":""}{m.quantity_change}</b></td><td>{m.notes||"—"}</td></tr>)}</tbody></table></div></section>
   </div>
   {showProduct&&<div className="modal-backdrop"><form className="modal" onSubmit={saveProduct}><div className="modal-title"><div><h2>{editingProduct?"Edit product":"New product"}</h2><p>{editingProduct?"Update catalogue details without changing stock.":"Add an item to the retail catalogue."}</p></div><button type="button" onClick={closeProductModal}>×</button></div><div className="form-grid"><label className="wide">Product name<input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/></label><label>SKU<input required value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/></label><label>Barcode<div className="barcode-input"><input value={productForm.barcode} onChange={e=>setProductForm({...productForm,barcode:e.target.value})} placeholder="Scan or enter barcode"/><button type="button" onClick={generateBarcode}>Generate</button></div></label>{productForm.barcode&&<div className="barcode-preview"><BarcodeSvg value={productForm.barcode}/></div>}<label>Category<input required value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})}/></label><label>Selling price<input required min="0" step=".01" type="number" value={productForm.price} onChange={e=>setProductForm({...productForm,price:e.target.value})}/></label><label>Cost price<input min="0" step=".01" type="number" value={productForm.cost} onChange={e=>setProductForm({...productForm,cost:e.target.value})}/></label>{!editingProduct&&<label>Opening stock<input min="0" step="1" type="number" value={productForm.opening} onChange={e=>setProductForm({...productForm,opening:e.target.value})}/></label>}<label>Reorder level<input min="0" step="1" type="number" value={productForm.reorder} onChange={e=>setProductForm({...productForm,reorder:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={closeProductModal}>Cancel</button><button disabled={loading} type="submit">{editingProduct?"Save changes":"Create product"}</button></div></form></div>}
   {showStock&&selectedProduct&&<div className="modal-backdrop"><form className="modal compact" onSubmit={changeStock}><div className="modal-title"><div><h2>Adjust stock</h2><p>{selectedProduct.name} · Current: {selectedProduct.stock}</p></div><button type="button" onClick={()=>setShowStock(false)}>×</button></div><label>Movement type<select value={stockForm.type} onChange={e=>setStockForm({...stockForm,type:e.target.value})}><option value="purchase">Receive stock</option><option value="adjustment_add">Positive adjustment</option><option value="adjustment_remove">Damaged / missing stock</option></select></label><label>Quantity<input autoFocus required min=".001" step=".001" type="number" value={stockForm.quantity} onChange={e=>setStockForm({...stockForm,quantity:e.target.value})}/></label><label>Notes<textarea required value={stockForm.notes} onChange={e=>setStockForm({...stockForm,notes:e.target.value})} placeholder="Supplier delivery, damage reason, correction…"/></label><div className="modal-actions"><button type="button" onClick={()=>setShowStock(false)}>Cancel</button><button disabled={loading} type="submit">Update stock</button></div></form></div>}
   {showLabels&&<div className="modal-backdrop print-modal"><div className="modal label-modal"><div className="modal-title no-print"><div><h2>Print barcode labels</h2><p>{labelIds.length} product labels selected.</p></div><button type="button" onClick={()=>setShowLabels(false)}>×</button></div><div className="label-sheet">{products.filter(p=>labelIds.includes(p.id)&&p.barcode).map(p=><article className="barcode-label" key={p.id}><strong>{p.name}</strong><span>{peso.format(p.price)}</span><BarcodeSvg value={p.barcode}/><small>{p.sku}</small></article>)}</div><div className="modal-actions no-print"><button type="button" onClick={()=>setShowLabels(false)}>Close</button><button type="button" onClick={()=>window.print()}>Print labels</button></div></div></div>}
  </section>:<section className="workspace staff-workspace"><header><div><p>Roles, permissions and account status</p><h1>Staff Access</h1></div><div className="header-actions"><button onClick={openStaff}>↻ Refresh</button></div></header><div className="inventory-body">{staffMessage&&<p className={staffMessage.includes("successfully")?"notice":"notice error"}>{staffMessage}</p>}<div className="role-guide"><article><span className="role-icon">A</span><div><strong>Administrator</strong><p>Checkout, products, inventory adjustments and staff-role management.</p></div></article><article><span className="role-icon cashier">C</span><div><strong>Cashier</strong><p>Point of sale and permitted transaction history only.</p></div></article></div><section className="inventory-card"><div className="inventory-card-title"><div><h2>Team members</h2><p>Create users in Supabase Authentication; they appear here automatically as cashiers.</p></div></div><div className="table-wrap"><table><thead><tr><th>Staff member</th><th>Role</th><th>Status</th><th>Added</th><th>Actions</th></tr></thead><tbody>{staff.map(member=><tr key={member.id}><td><strong>{member.full_name||member.email}</strong>{member.full_name&&<small className="cell-sub">{member.email}</small>}{member.id===session.user.id&&<span className="you-badge">You</span>}</td><td><select className="role-select" value={member.role} disabled={member.id===session.user.id} onChange={e=>updateStaff(member.id,{role:e.target.value as "admin"|"cashier"})}><option value="admin">Administrator</option><option value="cashier">Cashier</option></select></td><td><span className={member.active?"stock-badge":"stock-badge low"}>{member.active?"Active":"Inactive"}</span></td><td>{new Date(member.created_at).toLocaleDateString("en-PH",{dateStyle:"medium"})}</td><td><button className="stock-action" disabled={member.id===session.user.id} onClick={()=>updateStaff(member.id,{active:!member.active})}>{member.active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></section></div></section>}
 </main>
}
