"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type Branch={id:string;code:string;name:string};
type Check={key:string;label:string;value:number;status:"healthy"|"attention"|"critical";detail:string};
type Health={status:"healthy"|"attention"|"critical";checked_at:string;app_version:string;migration_version:string;recent_sales:number;active_staff:number;last_offline_sync:string|null;checks:Check[]};
export default function SystemHealthPanel({branches,localFailed}:{branches:Branch[];localFailed:number}){
 const [branch,setBranch]=useState("all"),[health,setHealth]=useState<Health|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{load("all")},[]);
 async function load(value=branch){setLoading(true);setMessage("");const {data,error}=await supabase.rpc("get_system_health",{p_branch_id:value==="all"?null:value});if(error)setMessage(error.message);else setHealth(data as Health);setLoading(false)}
 const totalAttention=(health?.checks??[]).filter(c=>c.status!=="healthy").length+localFailed;
 return <section className="workspace health-workspace"><header><div><p>Operational checks, exceptions and release readiness</p><h1>System Health</h1></div><div className="header-actions"><button disabled={loading} onClick={()=>load()}>↻ Run checks</button></div></header><div className="health-body">{message&&<p className="notice error">{message}</p>}<section className="health-overview"><div className={`health-orb ${health?.status??"loading"}`}><span>{loading?"…":health?.status==="healthy"?"✓":health?.status==="critical"?"!":"!"}</span></div><div><span>Overall status</span><h2>{loading?"Checking system…":health?.status==="healthy"?"All checks healthy":health?.status==="critical"?"Critical action required":"Review recommended"}</h2><p>{health?`${totalAttention} checks need attention · Last checked ${new Date(health.checked_at).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"})}`:"Run the database migration to activate diagnostics."}</p></div><label>Scope<select value={branch} onChange={e=>{setBranch(e.target.value);load(e.target.value)}}><option value="all">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></label></section><div className="health-kpis"><article><span>Application</span><strong>v{health?.app_version??"—"}</strong><small>Migration {health?.migration_version??"—"}</small></article><article><span>Sales in 24 hours</span><strong>{health?.recent_sales??0}</strong><small>Completed transactions</small></article><article><span>Active staff</span><strong>{health?.active_staff??0}</strong><small>Enabled accounts</small></article><article><span>Last offline sync</span><strong>{health?.last_offline_sync?new Date(health.last_offline_sync).toLocaleDateString("en-PH",{month:"short",day:"numeric"}):"None"}</strong><small>{health?.last_offline_sync?new Date(health.last_offline_sync).toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"}):"No synced offline sales"}</small></article></div><div className="health-grid"><section className="inventory-card"><div className="inventory-card-title"><div><h2>Operational checks</h2><p>Exceptions are calculated directly from current branch records.</p></div></div><div className="health-checks">{health?.checks.map(c=><article key={c.key}><span className={`check-icon ${c.status}`}>{c.status==="healthy"?"✓":"!"}</span><div><strong>{c.label}</strong><small>{c.detail}</small></div><b>{c.value}</b><span className={`check-state ${c.status}`}>{c.status}</span></article>)}</div></section><aside className="health-sidebar"><section><h2>Device sync</h2><strong className={localFailed?"health-danger":"health-good"}>{localFailed}</strong><p>Failed offline transactions stored on this device.</p></section><section><h2>Automated quality gate</h2><ul><li>Production build validation</li><li>Offline safety-rule tests</li><li>Rendered application smoke test</li><li>Runs on every GitHub push</li></ul></section></aside></div></div></section>
}
